hyperparams:
  learning_rate: optax.warmup_cosine_decay_schedule(1e-5, 1e-5, 3000, 80000, 1e-7)
  batch_size: 10
  diffusion_time_steps: 1000
  step: 99999
  save_ckpt: true
  ckpt_freq: 2000
  save_prediction: true
  gradient_clipping: 1.0
  ema_decay: 0.999
  load_vae_dir: /home/arezy/Desktop/fleiadex/outputs/2024-08-17/18-13-15/results/vae_ckpt
data_spec:
  _target_: fleiadex.data_module.FleiadexDataLoader
  pre_encoded: true
  data_dir: ./src/fleiadex/exp_data/satel_array_202312bandopt00_clear.npy
  validation_size: 0.1
  batch_size: 10
  fixed_normalisation_spec: null
  auto_normalisation: true
  output_image_size: 64
  image_channels: 4
  pre_split: false
  condition_length: 3
  sample_length: 1
nn_spec:
  sample_input_shape:
  - 64
  - 64
  - 1
  cond_input_shape:
  - 64
  - 64
  - 3
  spatial_down_sample_schedule:
  - 2
  - 2
  unet_use_residual: true
  down_sampler_type: conv
  down_sample_resnet_depth: 1
  down_sample_use_attention: true
  down_sample_attention_heads: 4
  down_sample_attention_use_memory_efficient: true
  down_sample_attention_use_dropout: true
  down_sample_attention_dropout_rate: 0.1
  bottleneck_resnet_depth: 1
  bottleneck_use_attention: true
  bottleneck_attention_heads: 4
  bottleneck_attention_use_memory_efficient: true
  bottleneck_attention_use_dropout: true
  bottleneck_attention_dropout_rate: 0.1
  up_sampler_type: interp2d
  up_sample_resnet_depth: 1
  up_sample_use_attention: true
  up_sample_attention_heads: 4
  up_sample_attention_use_memory_efficient: true
  up_sample_attention_use_dropout: true
  up_sample_attention_dropout_rate: 0.1
global_config:
  use_which_gpus: '0'
  hydra_full_error: '1'
  use_diffuser_backbone: unet_4d_conv_2d
  use_predictor_backbone: unet
  save_num_ckpts: 3
  compute_auxiliary_metric: true
